# !/usr/bin/env python3

#!/usr/bin/env python3

# Main.py file generated by New Project wizard

# Created:   Tue Sep 10 2024
# Processor: RPI3
# Compiler:  Python 3 (Proteus)

# Modules

import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)

motor_in1 = 17
motor_in2 = 25

GPIO.setup(motor_in1, GPIO.OUT)
GPIO.setup(motor_in2, GPIO.OUT)

def motor_forward():
    GPIO.output(motor_in1, GPIO.HIGH)
    GPIO.output(motor_in2, GPIO.LOW)

def motor_backward():
    GPIO.output(motor_in1, GPIO.LOW)
    GPIO.output(motor_in2, GPIO.HIGH)

def motor_stop():
    GPIO.output(motor_in1, GPIO.LOW)
    GPIO.output(motor_in2, GPIO.LOW)

try:
    while True:
        motor_forward()
        time.sleep(2)
        
        motor_backward()
        time.sleep(2)
        
        motor_stop()
        time.sleep(2)

except KeyboardInterrupt:
    motor_stop()
    GPIO.cleanup()
